name: Update LOC Stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs every night at midnight
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Count Lines of Code
        uses: anton-prizhiev/lines-of-code-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # This will scan all your public repositories
          requirements: 'all' 
          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update Lines of Code stats" || exit 0
          git push