name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important: Gives the bot permission to push changes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # This brings your README into the runner

      - name: Update README placeholders
        run: |
          REPOS=$(gh api users/Bretzz --jq '.public_repos')
          FOLLOWERS=$(gh api users/Bretzz --jq '.followers')

          sed -i "s/.*/$REPOS/g" README.md
          sed -i "s/.*/$FOLLOWERS/g" README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "docs: update profile stats" || echo "No changes to commit"
          git push